export const ARTISTS = [
  { name: "Avsluta", mix: "https://soundcloud.com/avsluta", b2b: null, b2bMix: null, otherMix: "https://soundcloud.com/monument-podcast/mnmt-395-avsluta" },
  { name: "Carrier b2b Gavsborg", mix: "https://soundcloud.com/driftingover", b2b: "Gavsborg", b2bMix: "https://soundcloud.com/platform/system-mix-001-gavsborg-time-cow" },
  { name: "Cassy", mix: "https://soundcloud.com/dgtl-festival/cassy-dgtl-amsterdam-080423" },
  { name: "CCL", mix: "https://soundcloud.com/dimensionsfestival/ccl-b2b-dj-voices" },
  { name: "Chen Ting" },
  { name: "Colleen", mix: "https://soundcloud.com/colleenplays", otherMix: "https://www.mixcloud.com/TheVinylFactory/vf-mix-14-colleen/" },
  { name: "Cosmo", mix: "https://soundcloud.com/platform/cosmo-vitelli-1" },
  { name: "Dana Kuehr", mix: "https://soundcloud.com/wakinglifeportugal/dana-kuehr-at-waking-life-2025" },
  { name: "Dasha Rush", mix: "https://soundcloud.com/draaimolen/dasha-rush-b2b-jakojako-at-draaimolen-festival-2024" },
  { name: "Devon Rexi", mix: "https://soundcloud.com/kioskradio/devon-rexi-kiosk-radio-15-02" },
  { name: "DJ Godfather", mix: "https://soundcloud.com/platform/dj-godfather" },
  { name: "Dj Masda", mix: "https://soundcloud.com/houghton-festival/dj-masda" },
  { name: "Dj Spence", mix: "https://soundcloud.com/thelotradio/in-the-open-takeover-with-dj-spence-snp-500-06-09-2024" },
  { name: "Dj Tobias", mix: "https://soundcloud.com/djtobias", otherMix: "https://soundcloud.com/djtobias/ionstorm006" },
  { name: "Dj Trystero", mix: "https://soundcloud.com/djtrystero", otherMix: "https://soundcloud.com/user-392749050/dj-trystero-dj-trystero-tape" },
  { name: "Djrum", mix: "https://soundcloud.com/dkmntl/dekmantel-podcast-267-djrum" },
  { name: "Drew McDowall", mix: "https://www.youtube.com/watch?v=F74YsmI911A" },
  { name: "Eduardo de la Calle", mix: "https://soundcloud.com/eduardodelacalle", otherMix: "https://soundcloud.com/platform/marc-pinol-b2b-eduarde-de-la-calle" },
  { name: "Edward", mix: "https://soundcloud.com/wakinglifeportugal/edward-at-outro-lado-waking" },
  { name: "Flo Masse", mix: "https://soundcloud.com/dimensionsfestival/dim299-flo-masse" },
  { name: "Garcon", mix: "https://soundcloud.com/garcon", otherMix: "https://soundcloud.com/thelotradio/pacific-mode-with-garc-on-and" },
  { name: "Glossy Mario", mix: "https://soundcloud.com/kioskradio/outsiders-glossy-60497867" },
  { name: "Gyrofield b2b Upsammy", mix: "https://soundcloud.com/noisily-festival/noisily-live-025-gyrofield", b2b: "Upsammy", b2bMix: "https://soundcloud.com/wakinglifeportugal/upsammy-at-praia-waking-life-24?in=upsammy/sets/jee&si=2d94bf6905c249fd8547c7ef63321c2a&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" },
  { name: "Haruka", mix: "https://soundcloud.com/haruka_ptc", otherMix: "https://soundcloud.com/buttersessions/butter-mix-61-haruka-future-terror" },
  { name: "HHY & The Kampala Unit", mix: "https://soundcloud.com/hhythekampalaunit", otherMix: "https://www.youtube.com/watch?v=w2dJpZ9bju8" },
  { name: "Jennifer Cardini", mix: "https://soundcloud.com/platform/jennifer-cardini-boiler-room-x-tropico-festival" },
  { name: "John McEntire", mix: "https://soundcloud.com/sam-prekop" },
  { name: "Kia", mix: "https://soundcloud.com/wakinglifeportugal/kia-at-waking-life-2025" },
  { name: "Kia b2b Richard Akingbehin", mix: "https://soundcloud.com/wakinglifeportugal/kia-at-waking-life-2025", b2b: "Richard Akingbehin", b2bMix: "https://soundcloud.com/richard-akingbehin/richard-akingbehin-draaimolen-x-sustain-release-tilburg-may-24" },
  { name: "Konduku", mix: "https://soundcloud.com/houghton-festival/recorded-at-houghton-konduku-2025" },
  { name: "Kuba'97", mix: "https://soundcloud.com/kuba97/kuba97-soleil-rouge-horst-2025" },
  { name: "Laima Adelaide", mix: "https://soundcloud.com/amlia", otherMix: "https://soundcloud.com/art-bei-ton/054laimaadelaide" },
  { name: "Lawrence", mix: "https://soundcloud.com/lawrence_dial/lawrence-live-garbicz-2018" },
  { name: "Magda", mix: "https://soundcloud.com/magda-official", otherMix: "https://www.youtube.com/watch?v=Ht_RshpD63s" },
  { name: "Mala", mix: "https://soundcloud.com/getdarker/dgital-mystikz-live-at-outlook-festival-2010" },
  { name: "Marylou", mix: "https://soundcloud.com/crackmagazine/crack-mix-599-marylou" },
  { name: "Melchor Productions Ltd b2b Lawrence", mix: "https://soundcloud.com/melchiorproductionsltd", b2b: "Lawrence", b2bMix: "https://soundcloud.com/lawrence_dial/lawrence-live-garbicz-2018", otherMix: "https://soundcloud.com/trommelmusic/trommel096-melchior-productions-ltd-live-own-productions-only" },
  { name: "Mike Servito", mix: "https://soundcloud.com/draaimolen/mike-servito-at-draaimolen-festival-2025-5" },
  { name: "Millie McKee", mix: "https://soundcloud.com/dimensionsfestival/dim335-millie-mckee" },
  { name: "Nicolini", mix: "https://soundcloud.com/nicoliniskinni4people" },
  { name: "NikNak", mix: "https://soundcloud.com/niknakdjmusic", otherMix: "https://www.youtube.com/watch?v=l_HlbAj9g9g" },
  { name: "Nosedrip", mix: "https://soundcloud.com/dkmntl/nosedrip-at-dekmantel-festival-2023" },
  { name: "OJOO", mix: "https://soundcloud.com/platform/system-mix-084-ojoo-gyal" },
  { name: "Olgica", mix: "https://soundcloud.com/kleinundhaarig/2024-olgica" },
  { name: "Om Unit", mix: "https://soundcloud.com/livity-sound/om-unit-livity-sound-mix-series-016" },
  { name: "Paquita Gordon", mix: "https://soundcloud.com/dkmntl/paquita-gordon-at-dekmantel-festival-2023" },
  { name: "Parallel 9", mix: "https://soundcloud.com/musicmanrecords/parallel-9-mix" },
  { name: "Phrex", mix: "https://soundcloud.com/phrex" },
  { name: "PLO Man", mix: "https://soundcloud.com/dkmntl/plo-man-at-dekmantel-festival-2023" },
  { name: "PLO MAN b2b Dj Spence", mix: "https://soundcloud.com/dkmntl/plo-man-at-dekmantel-festival-2023", b2b: "Dj Spence", b2bMix: "https://soundcloud.com/thelotradio/in-the-open-takeover-with-dj-spence-snp-500-06-09-2024" },
  { name: "Rene Wise", mix: "https://soundcloud.com/dkmntl/rene-wise-at-dekmantel-ten" },
  { name: "Rhadoo", mix: "https://soundcloud.com/cel-ce-asteapta/rhadoo-live-at-sunwaves" },
  { name: "Richard Akingbehin", mix: "https://soundcloud.com/richard-akingbehin/richard-akingbehin-draaimolen-x-sustain-release-tilburg-may-24" },
  { name: "Rroxymore", mix: "https://soundcloud.com/platform/rroxymore-1" },
  { name: "Sam Prekop & John Mc Entire", mix: "https://soundcloud.com/sam-prekop" },
  { name: "Samuel Rohrer & Elvind Aarset", mix: "https://soundcloud.com/samuel-rohrer-noreia", otherMix: "https://soundcloud.com/wakinglifeportugal/samuel-rohrer-live-at-cochilo-waking-life-23" },
  { name: "Serenne", mix: "https://soundcloud.com/serennee", otherMix: "https://soundcloud.com/isburning/serenne-isburning-176" },
  { name: "Simply Rockers Soundsystem", mix: "https://soundcloud.com/wakinglifeportugal/simply-rockers-sound-system" },
  { name: "Sina", mix: "https://soundcloud.com/anissina" },
  { name: "Sterac", mix: "https://soundcloud.com/dreaming-festival/steve-rachmad-aka-sterac-dreaming-festival-2025" },
  { name: "Tau Car", mix: "https://soundcloud.com/tau-car", otherMix: "https://soundcloud.com/192gmbh/tau-car-reptilian-mix-07" },
  { name: "Tiago", mix: "https://soundcloud.com/dkmntl/tiago-at-dekmantel-selectors-2019" },
  { name: "Vedic Roots x Simply Rockers", mix: "https://soundcloud.com/wakinglifeportugal/simply-rockers-sound-system" },
  { name: "Velv.93", mix: "https://soundcloud.com/kioskradio/velv-93-kiosk-radio-22-10-2022" },
  { name: "Vera", mix: "https://soundcloud.com/wakinglifeportugal/vera-at-outro-lado-waking-life-23" },
  { name: "Vlada", mix: "https://soundcloud.com/wakinglifeportugal/vlada-at-floresta-waking-life-23" },
];
